### PR TITLE
SLING-8032 - Add a MOJO which is able to validate JSON Feature file against the JSON Schema

### PR DESCRIPTION
**Pull request by simonetripodi**
initial checkin

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @simonetripodi - is this PR still good to go in after the recent refactoring of the codebase? 
The code itself looks good to me.

**Comment by simonetripodi** [comment]
Let me rebase `master` first, I need to double check! :P

**Comment by simonetripodi** [comment]
I would consider that MOJO as a special exception for configuration, respect to all other MOJOs, since it doesn't access to already parsed `Feature`, but it needs to access to the original JSON format to validate it, so I'd leave it as it is... at the end of the day it does nothing related to Feature itself, but it could become even a general-purpose JSON Schema MOJO.

@bosschaert @cziegeler WDYT?

**Comment by cziegeler** [comment]
While a general purpose JSON schema mojo would be nice, I see at least two problems with this:

- the configuration of where the json files are and which are included / excluded needs to be sync'ed with the configuration of where feature files are. Usually not a big deal as everyone uses the default configuration but as soon as you don't it can be come a subtle problem
- the reference to the json schema needs to reference an external schema for the general purpose (a url). This might become tricky as you make sure that your schema is available publically in the internet and is accessible at build time
I would rather prefer that we really only validate feature files. This way we can leverage the ProjectHelper.getFeatures to get the features. This method returns a map, and the key of each entry is the file path. This allows access to the raw feature files without having to repeat the configuration and the scanning logic. In addition if we bake in the schema for feature files we don't have any external dependency

**Comment by simonetripodi** [comment]
I got it, thanks @cziegeler for the feedback - I get back to work to apply those modifications!

**Comment by simonetripodi** [comment]
Currently, the Schema definition is in the `org.apache.sling.feature` module, see https://github.com/apache/sling-org-apache-sling-feature/blob/master/schema/Feature-1.0.0.schema.json - would it be OK to move it to the `slingfeature-maven-plugin` space?

I would suggest to have it in a single place to avoid synching multiple sources - WDYT?

**Comment by simonetripodi** [comment]
awesome - would it be OK to have it under `META-INF/feature` or better something else?

**Comment by cziegeler** [comment]
sounds good to me

**Comment by cziegeler** [comment]
Ah yes, you're right of course. the validation is too late.
So we should probably move the validation out of the mojo into the Preprocessor (which reads the json files). The method preprocessFeature looks like a good place to add the validation.
This method currently does

- variable substitution
- adds the "id" property if it is missing

So I think we should change that method to:
- add the "id" property if it is missing
- validate the feature
- variable substitution

**Comment by simonetripodi** [comment]
OK, so validation is turned _on_ by default?

**Comment by cziegeler** [comment]
Yes, an invalid json can't be read anyway

**Comment by simonetripodi** [comment]
Hi @cziegeler please check the updated branch, validation is now in the `Preprocessor` and proposed MOJO does not exist anymore.

Any feedback will be more than appreciated :)

**Comment by cziegeler** [comment]
Hi @simonetripodi Could you please rebase your branch against master? The listed changes contain a lot of stuff from master

**Comment by simonetripodi** [comment]
Sure, just give me few minutes!

**Comment by simonetripodi** [comment]
@cziegeler please refer to https://github.com/apache/sling-slingfeature-maven-plugin/pull/17

**Pull request closed without merging**
