### PR TITLE
SLING-8251 - Support checking dependencies for content packages

### PR DESCRIPTION
**Pull request by simonetripodi**
added required dependencies in order to invoke the new AnalyzerTask

### CODE REVIEW

**Comment by bosschaert** [comment]
The build failure is caused by the fact that the 1.0.4 release is under vote.

**Comment by bosschaert** [comment]
Not sure I get this PR. It's just extra maven dependencies without anything that is using it?

**Comment by simonetripodi** [comment]
@bosschaert the PR contains the org.apache.sling.feature.analyser version bump to 1.0.5-SNAPSHOT, which contains the new AnalizerTask implementation, aside the required dependencies to manipulate JCR Vault packages

**Comment by bosschaert** [comment]
Ah, those have scope: runtime, I didn't see that.

**Comment by simonetripodi** [comment]
@bosschaert just to mention that the new AnalyzerTask implementation is picked automaticaly up via the ServiceLoader, this is why no impl is required in the MOJO

**Comment by bosschaert** [comment]
LGTM then :)

**Comment by simonetripodi** [comment]
thanks for the review @bosschaert ! we need https://github.com/apache/sling-org-apache-sling-feature-analyser/pull/16 first, do you think it would be more appropriate waiting for released bundles being available on Central Repo and let the check pass, before merging?

**Pull request merged**
