### PR TITLE
SLING-9886 convert ITs post-execution script from Beanshell to Groovy

### PR DESCRIPTION
**Pull request by kwin**
Only the array initializers were converted from Java to Groovy style,
the rest was left untouched.

The changes exposes some actual IT failures

### CODE REVIEW

**Comment by cziegeler** [comment]
Changes look ok to me - if the project still builds with Java 8 and Java 11 afterwards, +1

**Comment by kwin** [comment]
Someone needs to fix the failing ITs. I don't know if those are actual bugs in the code or just flaws in the IT.

**Comment by cziegeler** [comment]
How many ITs are failing after the change?

**Comment by kwin** [comment]
```
[ERROR] The following builds failed:
[ERROR] *  apis-jar-wrapped-flattened-classes/pom.xml
[ERROR] *  apis-jar-wrapper-bundle/pom.xml
[ERROR] *  apis-jar/pom.xml
```
(https://ci-builds.apache.org/job/Sling/job/modules/job/sling-slingfeature-maven-plugin/job/PR-60/1/console)

**Comment by cziegeler** [comment]
Sounds doable, I think it makes sense to create a new issue to fix the ITs

**Comment by kwin** [comment]
So should I go ahead and merge and break the Jenkins build?

**Comment by cziegeler** [comment]
Yes and please create a new issue for the ITs - I'll try to look into that one then

**Pull request merged**
