### PR TITLE
Added the creation of the Generated Feature Model folder it is does n…

### PR DESCRIPTION
**Pull request by schaefa**
…ot exist. This can happen if there is no prior attachment or other FM generation and the Maven module in question is just doing the aggregation.

### CODE REVIEW

**Comment by schaefa** [comment]
This is based on ticket: https://issues.apache.org/jira/browse/SLING-10035

**Comment by bosschaert** [comment]
What are these failing CI runs about?

**Comment by schaefa** [comment]
You're guess is as good as mine. I see this as a root cause in the 'apis-jar-exported-package-no-classes' it:

Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://osgi.org/javadoc/r6/core//package-list
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0 (HttpURLConnection.java:1894)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream (HttpURLConnection.java:1492)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream (HttpsURLConnectionImpl.java:263)
    at org.apache.sling.feature.maven.mojos.apis.ApisUtil.getPackageList (ApisUtil.java:145)
    at org.apache.sling.feature.maven.mojos.apis.JavadocLinks.calculateLinks (JavadocLinks.java:44)
    at org.apache.sling.feature.maven.mojos.ApisJarMojo.onFeature (ApisJarMojo.java:585)
    at org.apache.sling.feature.maven.mojos.ApisJarMojo.execute (ApisJarMojo.java:407)

Master has the same issue. I think osgi.org is down.

**Comment by bosschaert** [comment]
Seems like the requested resource is available at https://docs.osgi.org/javadoc/r6/core/package-list

**Comment by karlpauls** [comment]
@bosschaert, yes - there is a glitch with the migration to eclipse. The website doesn't have any unqualified ://osgi.org anymore

**Comment by bosschaert** [comment]
@schaefa could you maybe fix that as part of this PR so that all the tests turn green again?

**Comment by schaefa** [comment]
@bosschaert Sure, I give it a try

**Comment by schaefa** [comment]
I did fix that (replace OSGi.org with docs.osgi.org) but locally my build is still failing due to an 403 HTTP error code when accessing the 'https://docs.osgi.org/javadoc/r6/core/package-list'.
I doubled checked the URL with curl and it works fine locally. I also tried 'http://' but the same.

**Pull request merged**
