### PR TITLE
SLING-8034 - SlingStart-m-p and SlingFeature-m-p packagetype clash

### PR DESCRIPTION
**Pull request by simonetripodi**
initial proposal

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @simonetripodi thanks for picking this up! 
I think there are also some references to `slingfeature` in src/main/resources...?

**Comment by simonetripodi** [comment]
aw, my bad, they were somehow filtered out :/ - I will update the PR!

**Comment by bosschaert** [comment]
Hi @simonetripodi I rebased your commit in d94bcbd4ba22f59970283060558b70d2ecf2f41a and its now merged. Many thanks for the contribution!

**Comment by simonetripodi** [comment]
A W E S O M E thanks for spending time on reviewing my submission! 🥇

**Pull request closed without merging**
